name: Deploy PR previews
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    branches:
      - main
concurrency: preview-${{ github.ref }}
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment variables
        run: |
          echo "REACT_APP_PREVIEW_BASE=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "REACT_APP_DEPLOY_ENV=PREVIEW" >> $GITHUB_ENV
          echo "REACT_APP_PUBLIC_URL=https://push-protocol.github.io/" >> $GITHUB_ENV
          echo "GITHUB_PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "ESLINT_NO_DEV_ERRORS=true" >> $GITHUB_ENV
          echo "TSC_COMPILE_ON_ERROR=true" >> $GITHUB_ENV
          echo "DISABLE_ESLINT_PLUGIN=true" >> $GITHUB_ENV
          echo "GENERATE_SOURCEMAP=true" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 20.x
          cache: yarn

      - name: Install and Build
        if: github.event.action != 'closed' # You might want to skip the build if the PR has been closed
        run: |
          yarn install --frozen-lockfile
          yarn build:pr:preview


      # Configure GitHub Pages for deployment
      - name: Setup Pages
        uses: actions/configure-pages@v3

      # Upload build artifacts for review
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: build

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1.4.7
        with:
          source-dir: ./build/
          umbrella-dir: pr-preview

      - uses: rossjrw/pr-preview-action@v1.4.7
        if: github.event.action == 'closed' && !github.event.pull_request.merged
        with:
          source-dir: ./build/
          action: remove